// <auto-generated />
namespace dynamicNSG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class operand2_in_rules : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(operand2_in_rules));
        
        string IMigrationMetadata.Id
        {
            get { return "201708251342058_operand2_in_rules"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
